@dominio = hola-codespace-zyet


GET https://{{dominio}}.onrender.com/demo/all


#####

POST https://{{dominio}}.onrender.com/demo/add
Content-Type: application/x-www-form-urlencoded

name=Johan&email=samseijuro@gmail.com


#####

DELETE GET https://{{dominio}}.onrender.com/demo/del
Content-Type: application/x-www-form-urlencoded

id=1